[package]
name = "juniper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
juniper = "0.15.9"
juniper_actix = "0.4.0"
actix-web = { version = "4.1.0", features = ["macros"] }
env_logger = "0.9.0"